HIVE-25404 insert merge partitioned
apache/hive pull request #2568
Opened 2021-08-06 13:20 UTC by kgyrtkirk

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2021-08-24 07:00 UTC, kasakrisz requested changes

2021-08-25 06:26 UTC, kgyrtkirk commented on ql/src/test/queries/clientpositive/merge_partitioned_insert.q
> +drop table t;
my original test case only had one case; later added a second
removed these `drop` statements as they are only needed from beeline

2021-08-25 06:28 UTC, kgyrtkirk commented on ql/src/test/queries/clientpositive/merge_partitioned_insert.q
> +merge into t1 t using u on t.id=u.id when not matched then insert (id) values (u.id);
no; the issue was a compilation - I didn't wanted to add a big explain which doesn't catch any part of the issue

2021-08-25 06:45 UTC, kgyrtkirk commented on ql/src/test/queries/clientpositive/merge_partitioned_insert.q
> +
makes sense...original test was only checking for the compilation error
I don't think we have this covered that well..so I've added the `select` statements

2021-08-25 07:01 UTC, kasakrisz approved these changes

2021-09-06 13:49 UTC, merged