HIVE-25637: Hive on Tez: inserting data failing into the non native hive external table managed by kafka storage handler
apache/hive pull request #2944
Opened 2022-01-12 11:05 UTC by abstractdog

### What changes were proposed in this pull request?
Supporting INSERT into a kafka table in a secure cluster. Further details are in JIRA description.

### Why are the changes needed?
INSERT into a kafka table failed.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Tested on cluster.

2022-01-12 13:38 UTC, maheshk114 approved these changes

2022-01-12 13:38 UTC, maheshk114 commented on ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
> +      if (kafkaBrokers != null && !kafkaBrokers.isEmpty()) {
The common code can be reused instead of another copy

2022-01-12 13:40 UTC, maheshk114 requested changes
Please fix the review comment

2022-01-12 14:07 UTC, maheshk114 approved these changes

2022-01-13 15:18 UTC, abstractdog commented
TestReplWithJsonMessageFormat failure is unrelated

2022-01-13 15:18 UTC, merged

2022-01-13 15:19 UTC, abstractdog commented
merged to master, thanks @maheshk114  for the review!