HIVE-26737: Subquery returning wrong results when database has materi…
apache/hive pull request #3761
Opened 2022-11-15 01:23 UTC by scarlin-cloudera

…alized views

When there is a materialized view in the materialized view registry, the HiveMaterializedViewASTSubQueryRewriteShuttle runs and rewrites some RelNodes and RexNodes.

On creation time, the HivePlannerContext is given the RexSubquery nodes which are used to see if it is a correlated subquery with an agg. In the case where the RexSubQuery was rewritten, the Context contains references to stale nodes. It loses the correlated subquery information and creates an incorrect query plan.

The boolean check for subqueries with agg is now done within the Calcite nodes rather than when checking the ASTNodes. It was only used at rule time, so it made more sense for the calculation of the boolean value to be done there, and it's safer in the long run (as opposed to just update the global context when a new RexSubQuery is created).

The HiveFilter and HiveProject will contain the structure holding the calculated correlation information. The information is done with a lazy fetch and only calculated when needed.

The HiveCorrelationInfo structure only contains information for the current subquery level, similar to the old code. A correlated variable cannot go down to a subquery within a subquery at this point.

### What changes were proposed in this pull request?

Specified in description above

### Why are the changes needed?

Specified in description above

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Added q test which failed before change, succeeds after

2022-11-18 12:22 UTC, kasakrisz requested changes

2022-11-18 12:22 UTC, kasakrisz commented on ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/correlation/CorrelationInfoVisitor.java
> +  }
Could you please add tests when a not expression has multiple subqueries as operands like
```
explain cbo
select id, int_col, year, month from t_test1 s where not (
  s.int_col in (select count(*) from t_test2 t2 where s.id = t2.id) and 
  s.int_col in (select count(*) from t_test3 t3 where s.id = t.3id)
);
```

2022-11-20 23:38 UTC, scarlin-cloudera commented on ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java
> +      HiveCorrelationInfo correlationInfo = project.getCorrelationInfos().get(0);
You can have two subqueries in 2 different columns which would show up as two different HiveCorrelationInfo objects?

2022-11-22 00:01 UTC, scarlin-cloudera commented on ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query1.q.out
> +        HiveFilter(condition=[IS NOT NULL(CAST(*(CAST(/($1, $2)):DECIMAL(21, 6), 1.2:DECIMAL(2, 1))):DECIMAL(24, 7))])
Good catch!

Looks like I missed this change, I thought I had only trivial changes.

After looking at this, there was indeed a change of behavior in that it was looking at multiple aggregates in the RelNode stack for "group by" statements when it should only look at the first aggregate.  I made the code change and this regression went away.

2022-11-30 07:54 UTC, kasakrisz commented on ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java
> +      HiveCorrelationInfo correlationInfo = project.getCorrelationInfos().get(0);
I managed to have more than one `CorrelationInfo`:
```
explain cbo
select
  year in (select year from t_test2 where t_test2.id = t_test1.id),
  month in (select month from t_test2 where t_test2.id = t_test1.id)
from t_test1;
```
but here we always get the 1st element of the list and `project.getCorrelationInfos()` is nowhere else is used or I'm missing something.

Could you please check why do we have to collect all `CorrelationInfo` objects

2022-12-02 00:28 UTC, scarlin-cloudera commented on ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java
> +      HiveCorrelationInfo correlationInfo = project.getCorrelationInfos().get(0);
Gonna check this tomorrow, but this is what I think is happening...

I think the rule just happens to get hit twice.  After the first correlation is grabbed, it creates a new filter with one less CorrelationInfo.  The rule gets triggered again and processes the second CorrelationInfo.

On my first pass, I did change this by putting in a for loop.  I had some changes in the plans when I tried that.  And I also figured that this makes the code review cleaner by not adding a for loop?  I can try it again though.  At least if I try it now, the next code review would be only the change of adding a for loop.  Just let me know and I'll try this.

2022-12-05 08:49 UTC, kasakrisz approved these changes

2022-12-05 08:49 UTC, merged