HIVE-27055: hive-exec typos part 3
apache/hive pull request #4035
Opened 2023-02-07 09:46 UTC by mlorek

### What changes were proposed in this pull request?
fix typos in comments and code

### Why are the changes needed?
to improve code quality

### Does this PR introduce _any_ user-facing change?
No (except debug logging)

### How was this patch tested?
build

2023-02-14 13:51 UTC, ayushtkn reviewed
Very quick look.
Refrain from changing public method names

2023-02-23 08:27 UTC, mlorek commented
@abstractdog any chance you could review it?

2023-02-23 09:03 UTC, abstractdog commented on ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
> +  private boolean isTableSatisfiesConfig(Table table) {
if we're about grammar, and this is a private method (we won't break anything), isn't it "doesTableSatisfyConfig instead?

2023-02-23 09:11 UTC, abstractdog requested changes
LGTM, 1 minor change request

2023-02-24 07:32 UTC, abstractdog approved these changes
+1

2023-02-24 07:33 UTC, merged