HIVE-26997: Iceberg: Vectorization gets disabled at runtime in merge-into statement
apache/hive pull request #4162
Opened 2023-03-27 18:35 UTC by deniskuzZ

### What changes were proposed in this pull request?

Fixed non-vectorization cause

### Why are the changes needed?

Performance

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

2023-03-29 06:28 UTC, kasakrisz requested changes

2023-03-29 06:28 UTC, kasakrisz commented on iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java
> +        SERDE_META_COLS.size() + (skipRowData || partitioned ? 0 : dataCols.size()));
is it `skipRowData && !partitioned` ?

2023-03-29 06:28 UTC, kasakrisz commented on iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_merge_mixed.q
> +-- SORT_QUERY_RESULTS
Please add test for merging partitioned iceberg tables.

2023-04-03 13:54 UTC, kasakrisz approved these changes
LGTM, pending test

2023-04-03 19:23 UTC, deniskuzZ commented on ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
> +    private String deletePrefix;
yep

2023-04-04 07:55 UTC, merged