HIVE-27960:Invalid function error when using custom udaf
apache/hive pull request #4955
Opened 2023-12-18 14:06 UTC by tc-gaoxiong

### What changes were proposed in this pull request?
[HIVE-27960](https://issues.apache.org/jira/browse/HIVE-27960) : Invalid function error when using custom udaf

### Why are the changes needed?
When a permanent udaf used before over() function, hive will throw invalid function error.

### Does this PR introduce _any_ user-facing change?
no

### Is the change a dependency upgrade?
no

### How was this patch tested?
on aliyun emr hive 2.3.9

2023-12-18 15:30 UTC, aturoczy approved these changes
+1 (If tests are passed)

2023-12-19 00:08 UTC, tc-gaoxiong commented
> +1 (If tests are passed)

10h... is this nomal?
![image](https://github.com/apache/hive/assets/9777973/0b18dc2b-8329-474b-b0a0-902abc4360ce)

2023-12-19 18:42 UTC, ayushtkn requested changes
This PR is for branch-2, Any fix first goes to master branch, check if the issue is reproducible on master branch. If yes, create a PR to master & add a test which can reproduce the issue

2023-12-20 05:47 UTC, tc-gaoxiong commented
> This PR is for branch-2, Any fix first goes to master branch, check if the issue is reproducible on master branch. If yes, create a PR to master & add a test which can reproduce the issue

This issue is reproducible on 4.0.0-beta-2-SNAPSHOT rfd92b3926393f0366b87cd55d5a0ad27968f18db (compile from master branch). Ok, i will create new PR to master and add test. Thanks.

2024-01-06 15:02 UTC, tc-gaoxiong commented
https://github.com/apache/hive/pull/4980, please review this PR for master. Thanks.

2024-01-07 01:02 UTC, closed without merging