HIVE-12371: Use DriverManager.getLoginTimeout() as fallback
apache/hive pull request #4964
Opened 2023-12-20 13:16 UTC by jneira-stratio

This way we would honour the previous behaviour if the new specific jdbc option is not set. Users may want to configure the timeout globally as before #1611

I've reused de jira ticket for the original request, please note if i should open a new one

Thanks!

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### Is the change a dependency upgrade?

### How was this patch tested?

2023-12-20 14:11 UTC, aturoczy commented
Hi @jneira-stratio 

Thanks for the PR. Yes, please open a new JIRA ticket and link the previous one. It is cleaner and helps the community when the release notes is generated.

2023-12-20 14:13 UTC, aturoczy requested changes
Please add a separated jira ticket for this issue.

Otherwise this change is OK. Thanks for your effort.

2023-12-30 09:06 UTC, ayushtkn requested changes
there are some 180+ test failures & all looks related
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4964/1/tests

2024-02-29 07:24 UTC, jneira-stratio commented
> there are some 180+ test failures & all looks related

They surely might be. However i cant see how the change _standalone_ could cause them as it is restoring a previous behaviour (prev to #1611) and DriverManager.loginTimeout default value is 0 afaics (the previous fixed default value).
Sorry i dont have time to take a deeper look, feel free to close it (well it will be closed auto anyway i guess).

2024-05-09 00:19 UTC, closed without merging