HIVE-28369: Fix LLAP cache proactive eviction
apache/hive pull request #5345
Opened 2024-07-12 08:54 UTC by ngsg

### What changes were proposed in this pull request?

This patch adds configuration/null checks to prevent NullPointerException.

### Why are the changes needed?

As I explained the JIRA ticket(HIVE-28369), Hive throws NPE during proactive eviction when `hive.llap.io.encode.enabled` is false. 

### Does this PR introduce _any_ user-facing change?

No

### Is the change a dependency upgrade?

No

### How was this patch tested?

Tested manually.
This cannot be tested using qtest because we cannot set up LLAP configuration in qfile as LLAP environment is initialized before test driver reads qfiles.

2024-07-12 14:30 UTC, kokila-19 approved these changes

2024-07-14 08:42 UTC, deniskuzZ commented on llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
> +    if (useLowLevelCache) {
`SimpleBufferManager` is used for `dataCache` when `useLowLevelCache` is `false`, so we should evict it as well

2024-07-14 08:44 UTC, deniskuzZ requested changes
`SimpleBufferManager` is used for `dataCache` when `useLowLevelCache` is `false`, so we should evict it as well

2024-07-15 03:31 UTC, ngsg commented
> `SimpleBufferManager` is used for `dataCache` when `useLowLevelCache` is `false`, so we should evict it as well

@deniskuzZ,  `SimpleBufferManager#markBuffersForProactiveEviction` always throws `UnsupportedOperationException`, so I excluded it when `useLowLevelCache == false`.

In fact, we don't have to check `dataCache` and `fileMetadataCache` because the first if-clause (`memoryManager == null`) ensures that `dataCache instanceof LowLevelCacheImpl` and `fileMetadataCache != null`. I didn't notice it and fixed my patch to check only `serdeCache`.

2024-07-15 10:33 UTC, deniskuzZ approved these changes
LGTM +1

2024-07-15 10:36 UTC, merged